apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: keycloak-service
  name: keycloak-service
  namespace: keycloak
spec:
  ports:
  - name: "8080"
    clusterIP: None
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: keycloak-service
  type: LoadBalancer
status:
  loadBalancer: {}
