apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keycloak
    spec:
      containers:
      - image: quay.io/keycloak/keycloak
        name: keycloak
        ports:
          - containerPort: 8080
        env:
          - name: KEYCLOAK_USER	
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          - name: DB_VENDOR
            value: postgres
          - name: DB_USER
            value: postgres
          - name: DB_PASSWORD
            value: 1m9a8z4urka
          - name: POSTGRES_USER
            value: keycloak
          - name: POSTGRES_PASSWORD
            value: 1m9a8z4urka
          - name: DB_ADDR
            value: postgres-service.keycloak.svc
          
