apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-svc
  name: postgres-svc
  namespace: keycloak
spec:
  clusterIP: None
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-svc
status:
  loadBalancer: {}
